import styles from './styles.module.scss';

export default function Partition() {
  return (
    <div className={styles.partition}>
      <p>PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM -  PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM -  PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM -  PROJETO DOM - PROJETO DOM - PROJETO DOM - PROJETO DOM -</p>
    </div>
  )
}