import Head from 'next/head'
import Hero from '@/src/components/Home/hero'
import HowWillHelp from '@/src/components/Home/howWillHelp'
import ModulesInfo from '@/src/components/Home/modulesInfo'
import Depositions from '@/src/components/Home/depositions'
import Partition from '@/src/components/Home/partition'
import Bio from '@/src/components/Home/bio'
import Prices from '@/src/components/Home/prices'
import Footer from '@/src/components/Home/footer'

import AOS from 'aos'
import "aos/dist/aos.css";
import { useEffect } from 'react'

export default function Home() {

  useEffect(() => {
    AOS.init();
  }, []);
  
  return (
    <>
      <Head>
        <title>PROJETO DOM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <Hero/>
        <HowWillHelp/>
        <ModulesInfo/> 
        <Depositions/>
        <Partition/>
        <Bio/>
        <Prices/>
        <Footer/>
      </main>
    </>
  )
}
